# keep version only for graphviz
version: '3.8'
services:
  gateway-agent:
    image: grafana/agent:v0.39.0
    volumes:
      - ./agent/config:/etc/agent-config
    entrypoint:
      - /bin/grafana-agent
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    environment:
      TEMPO_HOST: tempo:4317
      REMOTE_WRITE_HOST: mimir:9009
      LOKI_HOST: loki:3100
    networks:
      - bridge
    depends_on:
      - mimir
      - loki
      - tempo

  service:
    build:
      context: ./service
      args:
        - JDK_IMAGE=${JDK_IMAGE}
        - DISTRO=${DISTRO}
        - OTEL_JAVA_AGENT_VERSION=${OTEL_JAVA_AGENT_VERSION}
    deploy:
      replicas: 4
    networks:
      - bridge
    environment:
      - SERVICE_NAME=service
      - SERVICE_ENV=dev
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://gateway-agent:4317
      - OTEL_METRICS_EXPORTER=none
    depends_on:
      - mimir
      - loki
      - tempo

  client:
    build:
      context: ./client
      args:
        - JDK_IMAGE=${JDK_IMAGE}
        - DISTRO=${DISTRO}
        - OTEL_JAVA_AGENT_VERSION=${OTEL_JAVA_AGENT_VERSION}
    deploy:
      replicas: 4
    networks:
      - bridge
    environment:
      - SERVICE_NAME=client
      - SERVICE_ENV=dev
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://gateway-agent:4317
      - OTEL_METRICS_EXPORTER=none
    # ports:
    #   - 8080:8080
    depends_on:
      - mimir
      - loki
      - tempo
      - service

  curl:
    image: curlimages/curl:8.5.0
    networks:
      - bridge
    entrypoint: sh -c "watch -n 0.5 -d -- curl http://client:8080/hello 2>&1 > /dev/null"
    depends_on:
      - client

  loki:
    image: grafana/loki:2.9.3
    command: -config.file=/etc/loki/local-config.yaml -validation.reject-old-samples=false -query-scheduler.max-outstanding-requests-per-tenant=2048 -querier.max-outstanding-requests-per-tenant=2048
    volumes:
      - ./loki/:/etc/loki/:ro
    networks:
      - bridge

  mimir:
    image: grafana/mimir:2.11.0
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
    command: --config.file=/etc/mimir.yaml
    networks:
      - bridge

  tempo:
    image: grafana/tempo:2.3.1
    volumes:
      - ./tempo/tempo-local.yaml:/etc/tempo.yaml:ro
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      - bridge

  grafana:
    image: grafana/grafana-oss:10.1.5
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    networks:
      - bridge
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
    depends_on:
      - mimir
      - loki
      - tempo

networks:
  bridge: