server:
  log_level: debug

traces:
  configs:
  - name: tempo
    tail_sampling:
      policies:
        # sample traces that have a total duration longer than 100ms
        - type: latency
          latency:
            threshold_ms: 100
        # sample traces that contain at least one span with status code ERROR
        - type: status_code
          status_code:
            status_codes:
              - "ERROR"
    remote_write:
      - endpoint: ${TEMPO_HOST:-tempo:4317}
        insecure: true
    receivers:
      otlp:
        protocols:
          grpc: