# keep version only for graphviz
version: '3.8'
name: otel-lgtm-dotnet
services:
  otelcontribcol-gateway:
    image: otel/opentelemetry-collector-contrib:${OTEL_CONTRIB_COL}
    command: "--config /etc/otelcol-contrib/exporters.yml --config /etc/otelcol-contrib/extensions.yml --config /etc/otelcol-contrib/receivers.yml --config /etc/otelcol-contrib/pipeline.agent.yml --config /etc/otelcol-contrib/pipeline.logs.yml --config /etc/otelcol-contrib/pipeline.metrics.yml --config /etc/otelcol-contrib/pipeline.traces.yml"
    volumes:
      - ./otelcontribcol/gateway/:/etc/otelcol-contrib/:ro
    networks:
      - bridge
    ports:
      - 4317:4317
      - 4318:4318
    depends_on:
      - mimir
      - loki

  client:
    build: 
      context: ./client
      dockerfile: ../dotnet.Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcontribcol-gateway:4317
      - OTEL_METRIC_EXPORT_INTERVAL=1000
    networks:
      - bridge

  loki:
    image: grafana/loki@sha256:c59b9e928dffd375920b972e936c81e93bf14114c5229fae56a07cc47b15b475 #main with otlp support https://github.com/grafana/loki/pull/10727
    command: -config.file=/etc/loki/local-config.yaml -validation.reject-old-samples=false -query-scheduler.max-outstanding-requests-per-tenant=2048 -querier.max-outstanding-requests-per-tenant=2048
    volumes:
      - ./loki/:/etc/loki/:ro
    networks:
      - bridge

  mimir:
    image: grafana/mimir:2.11.0
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
    command: --config.file=/etc/mimir.yaml
    ports:
      - 9009:9009
    networks:
      - bridge

  tempo:
    image: grafana/tempo:2.3.1
    volumes:
      - ./tempo/tempo-local.yaml:/etc/tempo.yaml:ro
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      - bridge

  grafana:
    image: grafana/grafana-oss:10.3.1
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    networks:
      - bridge
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
    depends_on:
      - mimir
      - loki
      - tempo

networks:
  bridge: