server:
  port: 8080
  # required for grafana jvm dashboard
  # https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#tomcats-mbean-registry
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  datasource:
    show-sql: true
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/persons
    username: postgres
    password: ReallyBadPassword

management:
  otlp:      
    metrics:
      export:
        enabled: true
        step: 10s
        url: http://mimir:9009/otlp/v1/metrics
        # url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/otlp/v1/metrics
        # headers:
        #   Authorization: Basic ####

  metrics:
    tags:
      deployment.environment: '${deployment.environment}'
      service:
        name: '${service.name}'
        namespace: '${service.namespace}'
        version: '@project.version@'
        instance.id: '${service.instance.id}'
    distribution:
      percentiles:
        all: 0.5, 0.95, 0.99
      
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
    jmx:
      exposure:
        include: '*'