apiVersion: 1

# https://github.com/grafana/grafana/blob/1ea7dc92508ca51dfb29f54883a2a487f6441395/packages/grafana-o11y-ds-frontend/src/TraceToLogs/TraceToLogsSettings.tsx#L31
datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{${__tags}} | trace_id="${__trace.traceId}" | span_id="${__span.spanId}"'
      serviceMap:
        datasourceUid: 'mimir'
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'loki'