# keep version only for graphviz
version: '3.8'
services:
  loki:
    image: grafana/loki:2.9.4
    command: -config.file=/etc/loki/local-config.yaml -validation.reject-old-samples=false -query-scheduler.max-outstanding-requests-per-tenant=2048 -querier.max-outstanding-requests-per-tenant=2048
    volumes:
      - ./loki/:/etc/loki/:ro
    networks:
      - bridge

  mimir:
    image: grafana/mimir:2.11.0
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
    command: --config.file=/etc/mimir.yaml
    ports:
      - 9009:9009
    networks:
      - bridge

  tempo:
    image: grafana/tempo:2.3.1
    volumes:
      - ./tempo/tempo-local.yaml:/etc/tempo.yaml:ro
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      - bridge

  grafana:
    image: grafana/grafana-oss:10.3.1
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    networks:
      - bridge
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
    depends_on:
      - mimir
      - loki
      - tempo

networks:
  bridge: