# This is a configuration file for the OpenTelemetry Collector intended to be
# used in conjunction with the opentelemetry-otlp example.
#
# For more information about the OpenTelemetry Collector see:
#   https://github.com/open-telemetry/opentelemetry-collector
#
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp/mimir:
    metrics_endpoint: http://mimir:9009/otlp/v1/metrics
  otlphttp/victoriametrics:
    metrics_endpoint: http://victoriametrics:8428/opentelemetry/api/v1/push
  debug:
    verbosity: detailed

processors:
    cumulativetodelta:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      # processors: [cumulativetodelta]
      exporters: [debug, otlphttp/mimir, otlphttp/victoriametrics]
    logs:
      receivers: [otlp]
      exporters: [debug]