apiVersion: 1

datasources:
- name: VictoriaMetrics
  type: prometheus
  uid: victoriametrics
  access: proxy
  orgId: 1
  url: http://victoriametrics:8428
  basicAuth: false
  isDefault: false
  editable: false